package io.jeffrey.vector;

import org.junit.Assert;
import org.junit.Test;

public class GeneratedVectorRegisterCTest extends CommonVectorTestingBase {

    @Test
    public void testSET_11() throws Exception {
        final VectorRegisterC x = new VectorRegisterC();
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        assertEquals(0, x.x_0);
        assertEquals(0, x.y_0);
        assertEquals(0, x.x_1);
        assertEquals(0, x.y_1);
        assertEquals(0, x.x_2);
        assertEquals(0, x.y_2);
        assertEquals(0, x.x_3);
        assertEquals(0, x.y_3);
        assertEquals(0, x.x_4);
        assertEquals(0, x.y_4);
        assertEquals(0, x.x_5);
        assertEquals(0, x.y_5);
        assertEquals(0, x.x_6);
        assertEquals(0, x.y_6);
        assertEquals(0, x.x_7);
        assertEquals(0, x.y_7);
        assertEquals(0, x.x_8);
        assertEquals(0, x.y_8);
        assertEquals(0, x.x_9);
        assertEquals(0, x.y_9);
        assertEquals(0, x.x_10);
        assertEquals(0, x.y_10);
    }

    @Test
    public void testZERO_11() throws Exception {
        final VectorRegisterC x = new VectorRegisterC();
        x.set_0(3,5);
        assertEquals(3, x.x_0);
        assertEquals(5, x.y_0);
        x.set_1(3,5);
        assertEquals(3, x.x_1);
        assertEquals(5, x.y_1);
        x.set_2(3,5);
        assertEquals(3, x.x_2);
        assertEquals(5, x.y_2);
        x.set_3(3,5);
        assertEquals(3, x.x_3);
        assertEquals(5, x.y_3);
        x.set_4(3,5);
        assertEquals(3, x.x_4);
        assertEquals(5, x.y_4);
        x.set_5(3,5);
        assertEquals(3, x.x_5);
        assertEquals(5, x.y_5);
        x.set_6(3,5);
        assertEquals(3, x.x_6);
        assertEquals(5, x.y_6);
        x.set_7(3,5);
        assertEquals(3, x.x_7);
        assertEquals(5, x.y_7);
        x.set_8(3,5);
        assertEquals(3, x.x_8);
        assertEquals(5, x.y_8);
        x.set_9(3,5);
        assertEquals(3, x.x_9);
        assertEquals(5, x.y_9);
        x.set_10(3,5);
        assertEquals(3, x.x_10);
        assertEquals(5, x.y_10);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.zero_out_11();
        assertEquals(3, x.x_0);
        assertEquals(5, x.y_0);
        Assert.assertFalse(x.is_0_zero());
        assertEquals(3, x.x_1);
        assertEquals(5, x.y_1);
        Assert.assertFalse(x.is_1_zero());
        assertEquals(3, x.x_2);
        assertEquals(5, x.y_2);
        Assert.assertFalse(x.is_2_zero());
        assertEquals(3, x.x_3);
        assertEquals(5, x.y_3);
        Assert.assertFalse(x.is_3_zero());
        assertEquals(3, x.x_4);
        assertEquals(5, x.y_4);
        Assert.assertFalse(x.is_4_zero());
        assertEquals(3, x.x_5);
        assertEquals(5, x.y_5);
        Assert.assertFalse(x.is_5_zero());
        assertEquals(3, x.x_6);
        assertEquals(5, x.y_6);
        Assert.assertFalse(x.is_6_zero());
        assertEquals(3, x.x_7);
        assertEquals(5, x.y_7);
        Assert.assertFalse(x.is_7_zero());
        assertEquals(3, x.x_8);
        assertEquals(5, x.y_8);
        Assert.assertFalse(x.is_8_zero());
        assertEquals(3, x.x_9);
        assertEquals(5, x.y_9);
        Assert.assertFalse(x.is_9_zero());
        assertEquals(3, x.x_10);
        assertEquals(5, x.y_10);
        Assert.assertFalse(x.is_10_zero());
        assertEquals(0, x.x_11);
        assertEquals(0, x.y_11);
        Assert.assertTrue(x.is_11_zero());
    }

    @Test
    public void testIS_ZERO_11() throws Exception {
        final VectorRegisterC x = new VectorRegisterC();
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        Assert.assertFalse(x.is_11_zero());
        x.set_11(0,5);
        assertEquals(0, x.x_11);
        assertEquals(5, x.y_11);
        Assert.assertFalse(x.is_11_zero());
        x.set_11(3,0);
        assertEquals(3, x.x_11);
        assertEquals(0, x.y_11);
        Assert.assertFalse(x.is_11_zero());
        x.set_11(0,0);
        assertEquals(0, x.x_11);
        assertEquals(0, x.y_11);
        Assert.assertTrue(x.is_11_zero());
    }

    @Test
    public void testCOPY_11() throws Exception {
        final VectorRegisterC x = new VectorRegisterC();
        x.set_0(1,2);
        x.set_1(1,2);
        x.set_2(1,2);
        x.set_3(1,2);
        x.set_4(1,2);
        x.set_5(1,2);
        x.set_6(1,2);
        x.set_7(1,2);
        x.set_8(1,2);
        x.set_9(1,2);
        x.set_10(1,2);
        x.set_11(1,2);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.copy_from_0_to_11();
        assertEquals(1, x.x_11);
        assertEquals(2, x.y_11);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.copy_from_1_to_11();
        assertEquals(1, x.x_11);
        assertEquals(2, x.y_11);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.copy_from_2_to_11();
        assertEquals(1, x.x_11);
        assertEquals(2, x.y_11);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.copy_from_3_to_11();
        assertEquals(1, x.x_11);
        assertEquals(2, x.y_11);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.copy_from_4_to_11();
        assertEquals(1, x.x_11);
        assertEquals(2, x.y_11);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.copy_from_5_to_11();
        assertEquals(1, x.x_11);
        assertEquals(2, x.y_11);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.copy_from_6_to_11();
        assertEquals(1, x.x_11);
        assertEquals(2, x.y_11);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.copy_from_7_to_11();
        assertEquals(1, x.x_11);
        assertEquals(2, x.y_11);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.copy_from_8_to_11();
        assertEquals(1, x.x_11);
        assertEquals(2, x.y_11);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.copy_from_9_to_11();
        assertEquals(1, x.x_11);
        assertEquals(2, x.y_11);
        x.set_11(3,5);
        assertEquals(3, x.x_11);
        assertEquals(5, x.y_11);
        x.copy_from_10_to_11();
        assertEquals(1, x.x_11);
        assertEquals(2, x.y_11);
    }

    @Test
    public void testEXTRACT_11() throws Exception {
        final VectorRegisterC x = new VectorRegisterC();
        double[] data = new double[] {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
        x.set_11(-1,-2);
        x.extract_11(data, 0);
        x.extract_11(data, 5);
        x.extract_11(data, 8);
        assertEquals(-1,data[0]);
        assertEquals(-2,data[1]);
        assertEquals(2,data[2]);
        assertEquals(3,data[3]);
        assertEquals(4,data[4]);
        assertEquals(-1,data[5]);
        assertEquals(-2,data[6]);
        assertEquals(7,data[7]);
        assertEquals(-1,data[8]);
        assertEquals(-2,data[9]);
    }

    @Test
    public void testINJECT_11() throws Exception {
        final VectorRegisterC x = new VectorRegisterC();
        double[] data = new double[] {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
        x.inject_11(data, 0);
        assertEquals(0, x.x_11);
        assertEquals(1, x.y_11);
        x.inject_11(data, 6);
        assertEquals(6, x.x_11);
        assertEquals(7, x.y_11);
        x.inject_11(data, 8);
        assertEquals(8, x.x_11);
        assertEquals(9, x.y_11);
    }

    @Test
    public void testANGLES_11() throws Exception {
        final VectorRegisterC x = new VectorRegisterC();
        x.set_11_by_angle(0.5);
        assertEquals(0.8775825618903728, x.x_11);
        assertEquals(0.479425538604203, x.y_11);
        x.set_11_by_angle(1.5);
        assertEquals(0.0707372016677029, x.x_11);
        assertEquals(0.9974949866040544, x.y_11);
        x.set_11_by_angle(2.5);
        assertEquals(-0.8011436155469337, x.x_11);
        assertEquals(0.5984721441039564, x.y_11);
        double u, v;
        for(double theta = 0; theta < 7; theta += 0.1) {
            x.set_11_by_angle(theta);
            double omega = x.angle_11();
            u = x.x_11;
            v = x.y_11;
            x.set_11_by_angle(omega);
            assertEquals(u, x.x_11);
            assertEquals(v, x.y_11);
        }
    }

    @Test
    public void testALGEBRA11() throws Exception {
        final VectorRegisterC x = new VectorRegisterC();
        x.set_0(1,2);
        x.set_1(1,2);
        x.set_2(1,2);
        x.set_3(1,2);
        x.set_4(1,2);
        x.set_5(1,2);
        x.set_6(1,2);
        x.set_7(1,2);
        x.set_8(1,2);
        x.set_9(1,2);
        x.set_10(1,2);
        x.set_11(1,2);
        x.set_11(3,5);
        x.mult_11_by(4);
        assertEquals(12, x.x_11);
        assertEquals(20, x.y_11);
        x.div_11_by(2);
        assertEquals(6, x.x_11);
        assertEquals(10, x.y_11);
        x.add_0_to_11();
        assertEquals(7, x.x_11);
        assertEquals(12, x.y_11);
        x.set_11(1,2);
        x.set_11(3,5);
        x.mult_11_by(4);
        assertEquals(12, x.x_11);
        assertEquals(20, x.y_11);
        x.div_11_by(2);
        assertEquals(6, x.x_11);
        assertEquals(10, x.y_11);
        x.add_1_to_11();
        assertEquals(7, x.x_11);
        assertEquals(12, x.y_11);
        x.set_11(1,2);
        x.set_11(3,5);
        x.mult_11_by(4);
        assertEquals(12, x.x_11);
        assertEquals(20, x.y_11);
        x.div_11_by(2);
        assertEquals(6, x.x_11);
        assertEquals(10, x.y_11);
        x.add_2_to_11();
        assertEquals(7, x.x_11);
        assertEquals(12, x.y_11);
        x.set_11(1,2);
        x.set_11(3,5);
        x.mult_11_by(4);
        assertEquals(12, x.x_11);
        assertEquals(20, x.y_11);
        x.div_11_by(2);
        assertEquals(6, x.x_11);
        assertEquals(10, x.y_11);
        x.add_3_to_11();
        assertEquals(7, x.x_11);
        assertEquals(12, x.y_11);
        x.set_11(1,2);
        x.set_11(3,5);
        x.mult_11_by(4);
        assertEquals(12, x.x_11);
        assertEquals(20, x.y_11);
        x.div_11_by(2);
        assertEquals(6, x.x_11);
        assertEquals(10, x.y_11);
        x.add_4_to_11();
        assertEquals(7, x.x_11);
        assertEquals(12, x.y_11);
        x.set_11(1,2);
        x.set_11(3,5);
        x.mult_11_by(4);
        assertEquals(12, x.x_11);
        assertEquals(20, x.y_11);
        x.div_11_by(2);
        assertEquals(6, x.x_11);
        assertEquals(10, x.y_11);
        x.add_5_to_11();
        assertEquals(7, x.x_11);
        assertEquals(12, x.y_11);
        x.set_11(1,2);
        x.set_11(3,5);
        x.mult_11_by(4);
        assertEquals(12, x.x_11);
        assertEquals(20, x.y_11);
        x.div_11_by(2);
        assertEquals(6, x.x_11);
        assertEquals(10, x.y_11);
        x.add_6_to_11();
        assertEquals(7, x.x_11);
        assertEquals(12, x.y_11);
        x.set_11(1,2);
        x.set_11(3,5);
        x.mult_11_by(4);
        assertEquals(12, x.x_11);
        assertEquals(20, x.y_11);
        x.div_11_by(2);
        assertEquals(6, x.x_11);
        assertEquals(10, x.y_11);
        x.add_7_to_11();
        assertEquals(7, x.x_11);
        assertEquals(12, x.y_11);
        x.set_11(1,2);
        x.set_11(3,5);
        x.mult_11_by(4);
        assertEquals(12, x.x_11);
        assertEquals(20, x.y_11);
        x.div_11_by(2);
        assertEquals(6, x.x_11);
        assertEquals(10, x.y_11);
        x.add_8_to_11();
        assertEquals(7, x.x_11);
        assertEquals(12, x.y_11);
        x.set_11(1,2);
        x.set_11(3,5);
        x.mult_11_by(4);
        assertEquals(12, x.x_11);
        assertEquals(20, x.y_11);
        x.div_11_by(2);
        assertEquals(6, x.x_11);
        assertEquals(10, x.y_11);
        x.add_9_to_11();
        assertEquals(7, x.x_11);
        assertEquals(12, x.y_11);
        x.set_11(1,2);
        x.set_11(3,5);
        x.mult_11_by(4);
        assertEquals(12, x.x_11);
        assertEquals(20, x.y_11);
        x.div_11_by(2);
        assertEquals(6, x.x_11);
        assertEquals(10, x.y_11);
        x.add_10_to_11();
        assertEquals(7, x.x_11);
        assertEquals(12, x.y_11);
        x.set_11(1,2);
    }
}
